/**
* @author Jerson Poblete
* @date JULY-4-2017
* @description Repository for Constant variables.
*/
public without sharing class GlobalConstants {
	/*******************************************************************************************************
    * @description Constant variables for Case related data
    ********************************************************************************************************/
    //public static final String CASESTATUS = 'New'; 
    
}